### ISSUE TITLE
Can this mock server work over the network?

### ISSUE THREAD

**Issue by akoscsiszar** [densogiaichned/dsian.TwinCAT.Ads.Server.Mock#7]
In the examples provided, both the client and the server run as part of the same program. Is the server accessible over the network? If yes, is there a built-in command to listen to incoming connections?

**Comment by densogiaichned** [comment]
Hello,
only local connections are possible at the moment, what is intended for 'local' Tests  / Mocking, see
https://github.com/densogiaichned/dsian.TwinCAT.Ads.Server.Mock/blob/90a814ca55ea2165bec95c16294bdc9356d469d1/src/dsian.TwinCAT.Ads.Server.Mock/Mock.cs#L76

However, it`s possible to connect to the server remotly, via AmsTcpIpRouter, see offical [Beckhoff documentation](https://infosys.beckhoff.com/english.php?content=../content/1033/tc3_ads.net/index.html).
This requires additional software/setup, i.e. ADS route.

**Comment by akoscsiszar** [comment]
Thanks for the answer. Localhost is not bad. I am looking to mock a server to test a Java application. If I run both on the same host, or I use NGINX to forward a remote request to the localhost this would work then. Any tips on how to make the server listen? I.E. block the thread and listen for incoming connections on the localhost?

Great work on code BTW! This seems to be exactly what we are looking for.

**Comment by densogiaichned** [comment]
> Any tips on how to make the server listen? I.E. block the thread and listen for incoming connections on the localhost?

The server only listens on it's local ADS router. The client has to connect via it's own ADS router to the server via [ADS route](https://infosys.beckhoff.com/index.php?content=../content/1031/tc3_system/html/tcsysmgr_systemnode_subnodes_routes.htm).
